services:
  express-api-db:
    image: mongo:latest
    container_name: express-api-db
    ports:
      - "27017:27017"
    volumes:
      - express-api-db-data:/data/db
  express-api:
    build: .
    container_name: express-api
    environment:
      PORT: 3000
      SWAGGER_URL: "http://localhost:3000"
      MONGODB_URI: "mongodb://express-api-db:27017/express-api"
    ports:
      - "3000:3000"

volumes:
    express-api-db-data: